### ISSUE TITLE
Change Position

### ISSUE THREAD

**Issue by Simsonfanatiker** [aquapha/aq_hudv2#1]
Hey when I change the position in the AccountBalance.scss then it change it on the localhost server but not
 on my FiveM Server. What do I wrong?

**Comment by aquapha** [comment]
You have to make a new production build. Just type in ``npm run build`` to make a new prod build. After it finishes, just restart the script

**Comment by aquapha** [comment]
Haven't gotten a response less than 10 days. Issue is being closed due to being fixed or inactive.
