### ISSUE TITLE
SCRIPT ERROR: @aq_hudv2/server/main.lua:6: attempt to index a nil value (local 'xPlayer')

### ISSUE THREAD

**Issue by W0lv3sxD** [aquapha/aq_hudv2#2]
![image](https://user-images.githubusercontent.com/93610323/140640856-8e8ba8dd-c9c9-4c98-9afe-6856f0cc7f33.png)

This is spamming in the console after someone joins the server. It stops when the one who joined leaves the airport(entry). I would really appreciate your help by finding a fix for that.

**Comment by aquapha** [comment]
What version of ESX are you using?

**Comment by aquapha** [comment]
This is spamming, because when the player is creating a character, it starts looking for the "xPlayer" that does not exist yet. Will update it ASAP.

**Comment by W0lv3sxD** [comment]
Hey, thanks for your fast reply. I would have fixed it myself and opened a Pull request for you but I don't know anything about that stuff. 

Lemme know when it's updated. Thanks :)

**Comment by aquapha** [comment]
Updated 😊
